---
title: "Alternative trails"
author: "Carlos Cámara"
date: "24/3/2022"
output: html_document
---

```{r setup, include=FALSE}
library(htmltools)
library(leaflet)

# Load data
df <- read.csv("data/data.csv")

```

```{r ggplot_defaults}
# Custom ggplot theme.
mytheme_minimal <- theme_minimal(base_size = 12) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.caption = element_text(size = 8, face = "italic", 
                                    colour = "grey60"),
        plot.subtitle = element_text(size = 9, face = "plain", 
                                     colour = "grey50"),
        axis.ticks = element_line(colour = "grey80"),
        axis.ticks.length = unit(2, "pt"),
        strip.text = element_text(size = 12))

mytheme <- theme_minimal(base_size = 12) +
  theme(plot.caption = element_text(size = 8, face = "italic", 
                                    colour = "grey60"),
        plot.subtitle = element_text(size = 9, face = "plain", 
                                     colour = "grey50"),
        axis.ticks = element_line(colour = "grey80"),
        axis.ticks.length = unit(2, "pt"),
        strip.text = element_text(size = 12))

theme_set(mytheme_minimal)


```



### Interactive map
    
```{r}
groups <- c("Group1", "Group2")

getMkColor <- function(df) {
  sapply(df$data_type, function(data_type) {
  if(data_type == "Group1") {
    "orange"
  } else if(data_type == "Group2") {
    "green"
  } else {
    "red"
  } })
}

getMkIcon <- function(df) {
  sapply(df$category, function(category) {
  if(category == "dairy_products_ro") {
    "orange"
  } else if(data_type == "fruits_ro") {
    "fa-apple-alt"
  } else {
    "fa-apple-alt"
  } })
}

popup_content <- paste0(
      "<h5>", combined_df$name, "</h5>",
      
      "<table style='width:100%'>",
      
      "<tr>",
      "<th>Type</th>",
      "<td>", combined_df$type, "</td>",
      "</tr>",
      
      "<tr>",
      "<tr>",
      "<th>Address</th>",
      "<td>", combined_df$address, "</td>",
      "</tr>")

map <- leaflet(sd) %>% 
  addProviderTiles("CartoDB.Positron", group = "Positron (default)", 
                   layerId = "basetile") %>% 
  addTiles(group = "OSM") %>% 
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  # Add data
  addAwesomeMarkers(
    data = sd, ~longitude, ~latitude, 
    popup = ~popup_content,
    label = ~name,
    icon = awesomeIcons(
      library = "ion",
      # icon = ifelse(
      #   test = combined_df$data_type == "1 Outstanding",
      #   yes = "ion-android-star-outline",
      #   no = "ion-android-radio-button-off"
      # ),
      iconColor = "white",
      markerColor = getMkColor(combined_df)
    ) # end of icon
  ) %>%
  # Adds controls
  addLayersControl(
    baseGroups = c("Positron (default)", "OSM", "Toner", "Toner Lite"),
    overlayGroups = groups,
    options = layersControlOptions(collapsed = TRUE)
  ) %>% 
  addLegend("bottomright", 
    colors =c("orange", "green", "red"),
    labels= c("Sale points", "Producers", "Other"),
    title= "Type of data",
    opacity = 1) %>% 
  # addMiniMap(
  #   tiles = providers$CartoDB.Positron,
  #   toggleDisplay = TRUE ) %>% 
  leaflet::addMeasure()

map
```

